/**********************************************************************
 * Extern for omnivore
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var omnivore = {
  "csv": {
    "parse": function () {}
  },
  "geojson": function () {},
  "gpx": {
    "parse": function () {}
  },
  "kml": {
    "parse": function () {}
  },
  "polyline": {
    "parse": function () {}
  },
  "topojson": {
    "parse": function () {}
  },
  "wkt": {
    "parse": function () {}
  }
};
/**********************************************************************
 * End Generated Extern for omnivore
/**********************************************************************/
